image: gcr.io/tulip-infra/go-builder:3.6.1

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

stages:
  - build

build:
  stage: build
  script:
    - mkdir -p ./bin/linux_amd64
    - GO111MODULE=off go get -u github.com/client9/misspell/cmd/misspell
    - GO111MODULE=off go get -u github.com/bflad/tfproviderlint/cmd/tfproviderlint
    - GO111MODULE=off go get -u github.com/katbyte/terrafmt
    - GO111MODULE=off go get -u github.com/boyter/scc
    - GO111MODULE=off go get -u golang.org/x/tools/cmd/goimports
    - goimports -w ./twilio
    - gofmt -s -w ./twilio
    - CGO_ENABLED=0 GO111MODULE=on GOOS=linux GOARCH=amd64 go build -o ${PWD}/bin/linux_amd64/terraform-provider-twilio
  artifacts:
    paths:
      - ./bin/linux_amd64/terraform-provider-twilio
    expire_in: 3 months

